export const SET_ANIMATING='SET_ANIMATING';
export const CAROUSEL_NEXT='CAROUSEL_NEXT';
export const CAROUSEL_PREV='CAROUSEL_PREV';
export const START_CAROUSEL_ANIMATING='START_CAROUSEL_ANIMATING';
export const START_CAROUSEL_INDEX='START_CAROUSEL_INDEX';